import { Patient, Resource, Adversary, Alert } from './types';

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'P-001',
    name: 'Cpl. Miller, J.',
    rank: 'Corporal',
    history: { age: 28, fitnessLevel: 'ELITE', allergies: ['Penicillin'], bloodType: 'O+' },
    injuryType: 'Blast Injury / Thoracic Trauma',
    injuryCategory: 'BLAST',
    location: [34.5684, -116.3214],
    vitals: { hr: 142, bp: '82/40', spo2: 84, gcs: 8, rr: 32 },
    vitalsHistory: [
      { hr: 120, bp: '110/70', spo2: 95, gcs: 15, rr: 18, timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString() },
      { hr: 130, bp: '100/60', spo2: 92, gcs: 12, rr: 24, timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString() },
      { hr: 142, bp: '82/40', spo2: 84, gcs: 8, rr: 32, timestamp: new Date().toISOString() },
    ],
    severity: 'CRITICAL',
    predictedSurvivalMinutes: 14,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    lastUpdated: new Date().toISOString(),
    status: 'TRIAGED',
  },
  {
    id: 'P-002',
    name: 'Sgt. Chen, L.',
    rank: 'Sergeant',
    history: { age: 32, fitnessLevel: 'STANDARD', allergies: [], bloodType: 'A-' },
    injuryType: 'Gunshot Wound / Abdomen',
    injuryCategory: 'GSW',
    location: [34.5712, -116.3267],
    vitals: { hr: 110, bp: '110/70', spo2: 92, gcs: 13, rr: 24 },
    vitalsHistory: [
      { hr: 80, bp: '120/80', spo2: 98, gcs: 15, rr: 16, timestamp: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString() },
      { hr: 95, bp: '115/75', spo2: 96, gcs: 14, rr: 20, timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1.5).toISOString() },
      { hr: 110, bp: '110/70', spo2: 92, gcs: 13, rr: 24, timestamp: new Date().toISOString() },
    ],
    severity: 'SEVERE',
    predictedSurvivalMinutes: 38,
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    lastUpdated: new Date().toISOString(),
    status: 'PENDING',
  },
  {
    id: 'P-003',
    name: 'Pvt. Rodriguez, M.',
    rank: 'Private',
    history: { age: 21, fitnessLevel: 'STANDARD', allergies: [], bloodType: 'B+' },
    injuryType: 'Laceration / Left Arm',
    injuryCategory: 'BLUNT',
    location: [34.5678, -116.3241],
    vitals: { hr: 88, bp: '120/80', spo2: 98, gcs: 15, rr: 18 },
    vitalsHistory: [
      { hr: 85, bp: '120/80', spo2: 98, gcs: 15, rr: 18, timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString() },
      { hr: 88, bp: '120/80', spo2: 98, gcs: 15, rr: 18, timestamp: new Date().toISOString() },
    ],
    severity: 'STABLE',
    predictedSurvivalMinutes: 480,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    lastUpdated: new Date().toISOString(),
    status: 'TREATED',
  },
  {
    id: 'P-004',
    name: 'Lt. Amir, H.',
    rank: 'Lieutenant',
    history: { age: 35, fitnessLevel: 'ELITE', allergies: [], bloodType: 'AB+' },
    injuryType: 'IED Blast / Lower Limb Loss',
    injuryCategory: 'SHOCK',
    location: [34.5694, -116.3204],
    vitals: { hr: 155, bp: '70/30', spo2: 80, gcs: 7, rr: 36 },
    vitalsHistory: [{ hr: 155, bp: '70/30', spo2: 80, gcs: 7, rr: 36, timestamp: new Date().toISOString() }],
    severity: 'CRITICAL',
    predictedSurvivalMinutes: 8,
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    status: 'PENDING',
  },
  {
    id: 'P-005',
    name: 'Sgt. Davis, S.',
    rank: 'Sergeant',
    history: { age: 29, fitnessLevel: 'STANDARD', allergies: ['Latex'], bloodType: 'O-' },
    injuryType: 'Sniper GSW / Chest',
    injuryCategory: 'GSW',
    location: [34.5622, -116.3284],
    vitals: { hr: 125, bp: '95/65', spo2: 88, gcs: 12, rr: 28 },
    vitalsHistory: [{ hr: 125, bp: '95/65', spo2: 88, gcs: 12, rr: 28, timestamp: new Date().toISOString() }],
    severity: 'SEVERE',
    predictedSurvivalMinutes: 25,
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    status: 'PENDING',
  },
  {
    id: 'P-006',
    name: 'Cpl. Nakamura, T.',
    rank: 'Corporal',
    history: { age: 26, fitnessLevel: 'STANDARD', allergies: [], bloodType: 'A+' },
    injuryType: 'Shrapnel / Shoulder',
    injuryCategory: 'BLAST',
    location: [34.5722, -116.3164],
    vitals: { hr: 105, bp: '115/75', spo2: 95, gcs: 15, rr: 22 },
    vitalsHistory: [{ hr: 105, bp: '115/75', spo2: 95, gcs: 15, rr: 22, timestamp: new Date().toISOString() }],
    severity: 'MODERATE',
    predictedSurvivalMinutes: 120,
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    status: 'TRIAGED',
  },
  {
    id: 'P-007',
    name: 'Pvt. O\'Malley, K.',
    rank: 'Private',
    history: { age: 19, fitnessLevel: 'STANDARD', allergies: [], bloodType: 'B-' },
    injuryType: 'Blunt Trauma / Leg',
    injuryCategory: 'BLUNT',
    location: [34.5632, -116.3304],
    vitals: { hr: 90, bp: '120/80', spo2: 98, gcs: 15, rr: 18 },
    vitalsHistory: [{ hr: 90, bp: '120/80', spo2: 98, gcs: 15, rr: 18, timestamp: new Date().toISOString() }],
    severity: 'STABLE',
    predictedSurvivalMinutes: 600,
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    status: 'PENDING',
  },
  {
    id: 'P-008',
    name: 'Capt. Smirnova, A.',
    rank: 'Captain',
    history: { age: 40, fitnessLevel: 'ELITE', allergies: [], bloodType: 'AB-' },
    injuryType: 'Chemical Exposure / Inhalation',
    injuryCategory: 'CHEMICAL',
    location: [34.5602, -116.3244],
    vitals: { hr: 135, bp: '100/60', spo2: 82, gcs: 10, rr: 40 },
    vitalsHistory: [{ hr: 135, bp: '100/60', spo2: 82, gcs: 10, rr: 40, timestamp: new Date().toISOString() }],
    severity: 'CRITICAL',
    predictedSurvivalMinutes: 12,
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    status: 'PENDING',
  },
  {
    id: 'P-009',
    name: 'Sgt. Wilson, B.',
    rank: 'Sergeant',
    history: { age: 31, fitnessLevel: 'STANDARD', allergies: [], bloodType: 'O+' },
    injuryType: 'Flash Burn / 30% TBSA',
    injuryCategory: 'BURN',
    location: [34.5742, -116.3224],
    vitals: { hr: 120, bp: '105/70', spo2: 93, gcs: 14, rr: 24 },
    vitalsHistory: [{ hr: 120, bp: '105/70', spo2: 93, gcs: 14, rr: 24, timestamp: new Date().toISOString() }],
    severity: 'SEVERE',
    predictedSurvivalMinutes: 45,
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    status: 'TRIAGED',
  },
  {
    id: 'P-010',
    name: 'Cpl. Garcia, F.',
    rank: 'Corporal',
    history: { age: 24, fitnessLevel: 'STANDARD', allergies: [], bloodType: 'A-' },
    injuryType: 'Hemorrhagic Shock',
    injuryCategory: 'SHOCK',
    location: [34.5662, -116.3154],
    vitals: { hr: 148, bp: '65/35', spo2: 85, gcs: 6, rr: 34 },
    vitalsHistory: [{ hr: 148, bp: '65/35', spo2: 85, gcs: 6, rr: 34, timestamp: new Date().toISOString() }],
    severity: 'CRITICAL',
    predictedSurvivalMinutes: 5,
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    status: 'PENDING',
  },
  {
    id: 'P-011',
    name: 'Pvt. Lee, S.',
    rank: 'Private',
    history: { age: 22, fitnessLevel: 'STANDARD', allergies: [], bloodType: 'B+' },
    injuryType: 'Closed Fracture / Tibia',
    injuryCategory: 'BLUNT',
    location: [34.5702, -116.3314],
    vitals: { hr: 95, bp: '125/85', spo2: 99, gcs: 15, rr: 20 },
    vitalsHistory: [{ hr: 95, bp: '125/85', spo2: 99, gcs: 15, rr: 20, timestamp: new Date().toISOString() }],
    severity: 'STABLE',
    predictedSurvivalMinutes: 720,
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    status: 'PENDING',
  },
  {
    id: 'P-012',
    name: 'Sgt. Zuber, M.',
    rank: 'Sergeant',
    history: { age: 34, fitnessLevel: 'STANDARD', allergies: [], bloodType: 'O-' },
    injuryType: 'Internal Bleeding / Pelvis',
    injuryCategory: 'GSW',
    location: [34.5642, -116.3184],
    vitals: { hr: 130, bp: '90/50', spo2: 90, gcs: 11, rr: 26 },
    vitalsHistory: [{ hr: 130, bp: '90/50', spo2: 90, gcs: 11, rr: 26, timestamp: new Date().toISOString() }],
    severity: 'SEVERE',
    predictedSurvivalMinutes: 20,
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    status: 'PENDING',
  },
  {
    id: 'P-013',
    name: 'Lt. Thompson, R.',
    rank: 'Lieutenant',
    history: { age: 27, fitnessLevel: 'ELITE', allergies: [], bloodType: 'A+' },
    injuryType: 'Crush Injury / Bilateral Legs',
    injuryCategory: 'BLUNT',
    location: [34.5762, -116.3294],
    vitals: { hr: 140, bp: '85/45', spo2: 88, gcs: 9, rr: 30 },
    vitalsHistory: [{ hr: 140, bp: '85/45', spo2: 88, gcs: 9, rr: 30, timestamp: new Date().toISOString() }],
    severity: 'CRITICAL',
    predictedSurvivalMinutes: 18,
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    status: 'PENDING',
  },
  {
    id: 'P-014',
    name: 'Cpl. Singh, R.',
    rank: 'Corporal',
    history: { age: 25, fitnessLevel: 'STANDARD', allergies: [], bloodType: 'B-' },
    injuryType: 'Fragmentation Wound / Face',
    injuryCategory: 'BLAST',
    location: [34.5652, -116.3254],
    vitals: { hr: 115, bp: '110/70', spo2: 94, gcs: 13, rr: 24 },
    vitalsHistory: [{ hr: 115, bp: '110/70', spo2: 94, gcs: 13, rr: 24, timestamp: new Date().toISOString() }],
    severity: 'SEVERE',
    predictedSurvivalMinutes: 50,
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    status: 'TRIAGED',
  },
  {
    id: 'P-015',
    name: 'Pvt. Taylor, J.',
    rank: 'Private',
    history: { age: 20, fitnessLevel: 'STANDARD', allergies: [], bloodType: 'O+' },
    injuryType: 'Heat Exhaustion',
    injuryCategory: 'SHOCK',
    location: [34.5622, -116.3224],
    vitals: { hr: 110, bp: '115/75', spo2: 97, gcs: 15, rr: 20 },
    vitalsHistory: [{ hr: 110, bp: '115/75', spo2: 97, gcs: 15, rr: 20, timestamp: new Date().toISOString() }],
    severity: 'MODERATE',
    predictedSurvivalMinutes: 240,
    createdAt: new Date().toISOString(),
    lastUpdated: new Date().toISOString(),
    status: 'PENDING',
  }
];

export const MOCK_RESOURCES: Resource[] = [
  { id: 'AMB-02', type: 'AMBULANCE', name: 'Ambulance 02', status: 'OCCUPIED', location: [34.565, -116.320] },
  { id: 'MED-DELTA', type: 'MEDIC_TEAM', name: 'Medic Team Delta', status: 'STANDBY', location: [34.572, -116.328] },
  { id: 'HOSP-BASE', type: 'HOSPITAL', name: 'Forward Op Base Clinic', status: 'AVAILABLE', location: [34.580, -116.335] },
  { id: 'BASE-ALPHA', type: 'BASE', name: 'FOB Alpha Command', status: 'AVAILABLE', location: [34.555, -116.310] },
  { id: 'HELO-01', type: 'HELO', name: 'Dustoff 1 (Blackhawk)', status: 'AVAILABLE', location: [34.575, -116.315] },
  { id: 'MRAP-V1', type: 'MRAP', name: 'Iron Guard MRAP', status: 'AVAILABLE', location: [34.568, -116.325] },
  { id: 'APC-ST', type: 'APC', name: 'Striker APC MedEvac', status: 'OCCUPIED', location: [34.562, -116.318] },
  { id: 'DRN-SUPP', type: 'DRONE', name: 'Supply Drone X1', status: 'STANDBY', location: [34.570, -116.322] }
];

export const MOCK_ADVERSARIES: Adversary[] = [
  { id: 'ADV-01', type: 'INFANTRY', threatLevel: 'MEDIUM', location: [34.566, -116.310], lastSpotted: new Date().toISOString() },
  { id: 'ADV-02', type: 'ARMOR', threatLevel: 'HIGH', location: [34.575, -116.330], lastSpotted: new Date().toISOString() },
  { id: 'ADV-03', type: 'SNIPER', threatLevel: 'EXTREME', location: [34.560, -116.315], lastSpotted: new Date().toISOString() }
];

export const MOCK_ALERTS: Alert[] = [
  { id: '1', type: 'CRITICAL', message: 'CRITICAL: P-001 (Miller, J.) survival window dropping. < 14m remaining.', timestamp: new Date().toISOString(), patientId: 'P-001' },
  { id: '2', type: 'WARNING', message: 'MEDEVAC Helo-01 inbound to Sector 7. ETA 4m.', timestamp: new Date().toISOString() },
  { id: '3', type: 'INFO', message: 'Forward Op Base Clinic at 45% capacity.', timestamp: new Date().toISOString() }
];
